### ISSUE TITLE
Animate on Scroll library

### ISSUE THREAD

**Issue by lyquix-owner** [Lyquix/tpl_lyquix#16]
Check Animate on Scroll library: https://michalsnik.github.io/aos/ to explore if there is a better way to handle CSS animations during scrolling

**Comment by maustin92** [comment]
Covered in 781f3010b90059b23d2da5c8cf62acafa5d6431c

**Comment by lyquix-owner** [comment]
I don't think we should load this library. I just want us to find out how they handle scroll events, particularly on mobile, so that we can do manipulations of the DOM while scrolling is happening.

**Comment by lyquix-owner** [comment]
This may be useful: https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md
