### ISSUE TITLE
Useful string functions

### ISSUE THREAD

**Issue by lyquix-owner** [Lyquix/tpl_lyquix#17]
Check possible useful string manipulation functions and add them to the String prototype:

Inspiration
https://vocajs.com/ 
http://locutus.io/php/

Example functions:
* Count words
* Split chars
* Split words
* HTML encode
* HTML decode
* sprintf
* Insert
* Slugify
* Reverse
* Strip tags
* Clean HTML (remove specific tags and/or attributes)

**Comment by maustin92** [comment]
Support for voca covered in 8f4c9db90c54de0bce031393b9514e24ce70788b

**Comment by lyquix-owner** [comment]
I don't know if we want to load the whole library. I was thinking we select specific useful functions and incorporate them into our own library. We need to discuss first what functions (if any) would be picked.
